# Generated by Django 5.2.2 on 2025-06-17 19:01

from django.db import migrations


def create_sample_products(apps, schema_editor):
    Producto = apps.get_model("productos", "Producto")

    productos_iniciales = [
        {
            "nombre": "Labial Matte Rojo Clásico",
            "descripcion": "Labial de larga duración con acabado mate en tono rojo clásico. Fórmula hidratante que no reseca los labios.",
            "precio": 25.99,
            "iva": 15,
            "imagen": "productos/samples/lipstick.jpg",
        },
        {
            "nombre": "Base de Maquillaje Full Coverage",
            "descripcion": "Base de maquillaje de cobertura completa para todo tipo de piel. Disponible en múltiples tonos.",
            "precio": 42.50,
            "iva": 15,
            "imagen": "productos/samples/foundation.jpg",
        },
        {
            "nombre": "Sérum Vitamina C Anti-Edad",
            "descripcion": "Sérum facial con vitamina C pura para iluminar y rejuvenecer la piel. Ideal para uso diario.",
            "precio": 35.75,
            "iva": 0,
            "imagen": "productos/samples/serum-vitaminc.jpg",
        },
        {
            "nombre": "Paleta de Sombras Neutras",
            "descripcion": "Paleta con 12 sombras en tonos neutros y tierra. Perfecta para looks naturales y sofisticados.",
            "precio": 48.00,
            "iva": 15,
            "imagen": "productos/samples/eyeshadow-palette.jpg",
        },
        {
            "nombre": "Crema Hidratante Facial Noche",
            "descripcion": "Crema nutritiva para uso nocturno con ácido hialurónico y péptidos. Regenera la piel mientras duermes.",
            "precio": 29.99,
            "iva": 0,
            "imagen": "productos/samples/cream-jar.jpg",
        },
        {
            "nombre": "Máscara de Pestañas Volumen",
            "descripcion": "Máscara que proporciona volumen extremo y alarga las pestañas. Resistente al agua.",
            "precio": 18.50,
            "iva": 15,
            "imagen": "productos/samples/mascara.jpg",
        },
        {
            "nombre": "Perfume Floral Elegante 50ml",
            "descripcion": "Fragancia floral con notas de jazmín, rosa y bergamota. Perfecta para el día a día.",
            "precio": 65.00,
            "iva": 15,
            "imagen": "productos/samples/perfume.jpg",
        },
        {
            "nombre": "Exfoliante Facial Suave",
            "descripcion": "Exfoliante facial con microperlas naturales. Remueve células muertas y suaviza la piel.",
            "precio": 22.75,
            "iva": 0,
            "imagen": "productos/samples/face-scrub.jpg",
        },
        {
            "nombre": "Delineador Líquido Negro",
            "descripcion": "Delineador de ojos líquido con punta fina para trazos precisos. Larga duración y resistente al agua.",
            "precio": 15.99,
            "iva": 15,
            "imagen": "productos/samples/eyeliner.jpg",
        },
        {
            "nombre": "Protector Solar Facial SPF 50",
            "descripcion": "Protector solar facial de amplio espectro. No comedogénico y con base para maquillaje.",
            "precio": 28.50,
            "iva": 0,
            "imagen": "productos/samples/sunscreen.jpg",
        },
    ]

    for producto_data in productos_iniciales:
        Producto.objects.get_or_create(
            nombre=producto_data["nombre"], defaults=producto_data
        )


def remove_sample_products(apps, schema_editor):
    Producto = apps.get_model("productos", "Producto")
    nombres_productos = [
        "Labial Matte Rojo Clásico",
        "Base de Maquillaje Full Coverage",
        "Sérum Vitamina C Anti-Edad",
        "Paleta de Sombras Neutras",
        "Crema Hidratante Facial Noche",
        "Máscara de Pestañas Volumen",
        "Perfume Floral Elegante 50ml",
        "Exfoliante Facial Suave",
        "Delineador Líquido Negro",
        "Protector Solar Facial SPF 50",
    ]
    Producto.objects.filter(nombre__in=nombres_productos).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_sample_products, remove_sample_products),
    ]
