version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: practicatpe2
      POSTGRES_USER: practicausr25
      POSTGRES_PASSWORD: practic35
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    volumes:
      - ./media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: